<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CALVDQI" failures="0" tests="2" name="day22nov23.AnnotationDemo5" time="0.048" errors="1" timestamp="2023-11-22T14:03:04 IST" skipped="0">
  <testcase classname="day22nov23.AnnotationDemo5" name="reg" time="0.030">
    <error message="Method day22nov23.AnnotationDemo5.reg() didn&#039;t finish within the time-out 10" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method day22nov23.AnnotationDemo5.reg() didn't finish within the time-out 10
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:484)
at day22nov23.AnnotationDemo5.reg(AnnotationDemo5.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </error>
  </testcase> <!-- reg -->
  <testcase classname="day22nov23.AnnotationDemo5" name="Login" time="0.018"/>
</testsuite> <!-- day22nov23.AnnotationDemo5 -->
